### ISSUE TITLE
Fails and looses all results if directory "results" not exists yet

### ISSUE THREAD

**Issue by akurilov** [vladislav-kulakovsky/Java-RMI-client-server-with-concurrency#2]
> $ ./run_test.py 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Server started...
client started with 1 threads
client started with 2 threads
client started with 3 threads
client started with 4 threads
client started with 5 threads
client started with 6 threads
client started with 7 threads
client started with 8 threads
client started with 9 threads
client started with 10 threads
client started with 20 threads
client started with 30 threads
client started with 40 threads
client started with 50 threads
client started with 60 threads
client started with 70 threads
client started with 80 threads
client started with 90 threads
client started with 100 threads
Traceback (most recent call last):
  File "./run_test.py", line 57, in <module>
    print_to_csv(result)
  File "./run_test.py", line 26, in print_to_csv
    with open('results/result.csv', 'w', newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: 'results/result.csv'

**Comment by vladislav-kulakovsky** [comment]
All error with directory fixed
